print("This is the 4th day im learning git and github")
print("This is the 5th day im leanrning git and github")
print("Trying to pull from github to local")
print(This is a known mistake)
prin (this is also a known mistake)